version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true # Fix potential hot-reloading issues on some systems
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/app
    environment:
      # Add any backend environment variables here
      pass: 123
    depends_on:
      # Add any services the backend depends on (e.g., database) here
      []