apiVersion: v1
kind: Service
metadata:
  name: codegen-frontend-service
spec:
  selector:
    app: codegen-frontend
  ports:
    - protocol: TCP
      port: 80      # The port clients will access on the Node IP
      targetPort: 3000 # The port the container is listening on
      nodePort: 30080  # The port exposed on each Node's IP (choose a free port in the range 30000-32767)
  type: NodePort